(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



`Private`PainleveIIPositive["Pos"] =`ScaledPositive`ScaledPainleveIIPositive;
Begin["`ScaledPositive`"];


S[s_,k_?EvenQ]:=({
 {1, s[k]},
 {0, 1}
});
S[s_,k_?OddQ]:=({
 {1, 0},
 {s[k], 1}
});
SL[s_]:=({
 {1, 0},
 {1/s[2], 1}
});
SP1[s_] :=({
 {0, s[2]},
 {-1/s[2], 0}
});
SU[s_] :=({
 {1, -1/s[2]},
 {0, 1}
});
SP2[s_] :=Inverse[({
 {0, 1/s[2]},
 {-s[2], 0}
})];


\[Sigma]3=({
 {1, 0},
 {0, -1}
});

g[z_]:=-I 4/3 (I)^(-3/2)(I(z+I/Sqrt[2]))^(3/2) (-(I)^(-3/2)(I(z-I/Sqrt[2]))^(3/2));
\[Theta][z_]:=I(4/3 z^3 + z);

\[CapitalDelta][z_]:= (SqrtBranch[z-I/ Sqrt[2],\[Pi]/2] SqrtBranch[z+I/ Sqrt[2],\[Pi]/2] - 1/Sqrt[2])/(SqrtBranch[z-I/ Sqrt[2],\[Pi]/2] SqrtBranch[z+I/ Sqrt[2],\[Pi]/2] + 1/Sqrt[2]);
\[Nu][s_]:=1/(I \[Pi]) Log[I s[2]];
\[Delta][s_,z_]:=\[CapitalDelta][z]^(-\[Nu][s]/2);

\[Beta][z_]:=PowerBranch[z+I/Sqrt[2],1/4,\[Pi]/2] PowerBranch[z-I/Sqrt[2],-1/4,\[Pi]/2];
\[Beta]p[z_]:=PowerBranch[z+I/Sqrt[2],1/4,0] PowerBranch[z-I/Sqrt[2],-1/4,0];
\[Beta]m[z_]:=PowerBranch[z+I/Sqrt[2],1/4,\[Pi]] PowerBranch[z-I/Sqrt[2],-1/4,\[Pi]];
Y[z_]:=1/2 ({
 {\[Beta][z]+\[Beta][z]^(-1), (\[Beta][z]-\[Beta][z]^(-1))},
 {(\[Beta][z]-\[Beta][z]^(-1)), \[Beta][z]+\[Beta][z]^(-1)}
});
\[CapitalPhi][s_,t_,z_]:=Y[z].MatrixExp[-t g[z] \[Sigma]3].({
 {\[Delta][s,z], 0},
 {0, 1/\[Delta][s,z]}
});
\[CapitalPhi][s_,t_,z_?(ZeroQ[Re[#]]&)]:=\[CapitalPhi][s,t,z+$MachineEpsilon];

\[CapitalPhi]in[s_,t_,z_]:=Inverse[\[CapitalPhi][s,t,z]];
\[CapitalPhi]in[s_,t_,z_?(ZeroQ[Re[#]]&)]:=\[CapitalPhi]in[s,t,z+$MachineEpsilon];
Clear[GG,GGL,GGU];
GG[_,_][_?InfinityQ]:=IdentityMatrix[2];
GG[{t_,s_},2][z_]:=\[CapitalPhi][s,t,z].S[s,2].Inverse[\[CapitalPhi][s,t,z]];

GGL[_][_?InfinityQ]:=IdentityMatrix[2];
GGL[{t_,s_}][z_]:=\[CapitalPhi][s,t,z].Inverse[SL[s]].Inverse[\[CapitalPhi][s,t,z]];


GG[{t_,s_},1][z_]:=\[CapitalPhi][s,t,z].S[s,1].SL[s].Inverse[\[CapitalPhi][s,t,z]];
GG[{t_,s_},6][z_]:=\[CapitalPhi][s,t,z].SU[s].S[s,6].Inverse[\[CapitalPhi][s,t,z]];
GG[{t_,s_},4][z_]:=\[CapitalPhi][s,t,z].S[s,4].SU[s].Inverse[\[CapitalPhi][s,t,z]];
GG[{t_,s_},3][z_]:=\[CapitalPhi][s,t,z].SL[s].S[s,3].Inverse[\[CapitalPhi][s,t,z]];
GG[{t_,s_},5][z_]:=\[CapitalPhi][s,t,z].S[s,5].Inverse[\[CapitalPhi][s,t,z]];
GGU[_][_?InfinityQ]:=IdentityMatrix[2];
GGU[{t_,s_}][z_]:=\[CapitalPhi][s,t,z].Inverse[SU[s]].Inverse[\[CapitalPhi][s,t,z]];
\[CapitalPhi]\[Theta]b//Clear;
\[CapitalPhi]\[Theta]b[s_,t_,z_]:=\[CapitalPhi][s,t,z].MatrixExp[t \[Theta][z] \[Sigma]3];
\[CapitalPhi]\[Theta][s_,t_,z_]:=\[CapitalPhi]\[Theta]b[s,t,z];
\[CapitalPhi]\[Theta][_,_,_?InfinityQ]:=IdentityMatrix[2];


GGTC[{t_,s_},1][z_]:=(\[Piecewise]{
 {S[s,2].Inverse[SL[s]], Re[z]<0},
 {SL[s], True}
}).\[CapitalPhi]in[s,t,z];
GGTC[{t_,s_},2][z_]:=S[s,2].\[CapitalPhi]in[s,t,z];
GGTC[{t_,s_},3][z_]:=\[CapitalPhi]in[s,t,z];
GGBC[{t_,s_},1][z_]:=(\[Piecewise]{
 {SU[s], Re[z]<0},
 {S[s,5].Inverse[SU[s]], True}
}).\[CapitalPhi]in[s,t,z];
GGBC[{t_,s_},2][z_]:=S[s,5].\[CapitalPhi]in[s,t,z];
GGBC[{t_,s_},3][z_]:=\[CapitalPhi]in[s,t,z];

GGMC[{t_,s_},1][z_]:=\[CapitalPhi]in[s,t,z];
GGMC[{t_,s_},2][z_]:=S[s,1].S[s,2].S[s,3].S[s,4].(\[Piecewise]{
 {SU[s], Re[z]<=0},
 {S[s,5].Inverse[SU[s]], True}
}).\[CapitalPhi]in[s,t,z-3$MachineEpsilon];
GGMC[{t_,s_},3][z_]:=S[s,1].S[s,2].S[s,3].\[CapitalPhi]in[s,t,z];
GGMC[{t_,s_},4][z_]:=S[s,1].(\[Piecewise]{
 {S[s,2].Inverse[SL[s]], Re[z]<0},
 {SL[s], True}
}).\[CapitalPhi]in[s,t,z];


rngg={0.5,3.8};
rngg2={0.5,3.8};


Cdefs[n_]:={
{Function[t,({
 {I/Sqrt[2], -(I/Sqrt[2])},
 {t^(2/3), -t^(2/3)}
})],({
 {Line[I rngg], n},
 {Line[Exp[-\[Pi]/6 I] rngg], n},
 {Line[Exp[-5  \[Pi]/6 I] rngg], n},
 {Line[{Exp[- \[Pi]/6 I],Exp[-5\[Pi]/6I]}rngg[[1]]] , n+18},
 {Line[{Exp[-5\[Pi]/6I],I}rngg[[1]]] , n+18},
 {Line[{I,Exp[-\[Pi]/6I]}rngg[[1]]] , n+18}
})},
{Function[t,({
 {0},
 {t^(1/2)}
})],({
 {Line[Exp[-I \[Pi]/4] rngg], n+4},
 {Line[Exp[I \[Pi]/4] rngg], n},
 {Line[Exp[3I \[Pi]/4] rngg], n+4},
 {Line[Exp[-3I \[Pi]/4] rngg], n},
 {Line[{Exp[I \[Pi]/4],Exp[-I \[Pi]/4]} rngg[[1]]], n+6},
 {Line[{Exp[-I \[Pi]/4],Exp[-3 I \[Pi]/4]} rngg[[1]]], n+6},
 {Line[{Exp[-3 I \[Pi]/4],Exp[3 I \[Pi]/4]} rngg[[1]]], n+6},
 {Line[{Exp[3 I \[Pi]/4],Exp[ I \[Pi]/4]} rngg[[1]]], n+6}
})}};
Gf[x_]:={({
 {GG[x,2], GG[x,5]},
 {GGL[x], GGU[x]},
 {GGL[x], GGU[x]},
 {GGTC[x,1], GGBC[x,1]},
 {GGTC[x,2], GGBC[x,2]},
 {GGTC[x,3], GGBC[x,3]}
}),({
 {GG[x,6]},
 {GG[x,1]},
 {GG[x,3]},
 {GG[x,4]},
 {GGMC[x,1]},
 {GGMC[x,2]},
 {GGMC[x,3]},
 {GGMC[x,4]}
})}


slvr//Clear;slvr:=slvr=ScaledRHSolver[Cdefs[36]];


ScaledPainleveIIPositive[sin_,x_]:=Module[{s},
{s[1],s[2],s[3]}=sin;
{s[4],s[5],s[6]}=-Array[s,3];
Quiet[-(1/(\[Pi] I)) Total[DomainIntegrate/@slvr[x^(3/2),Gf[{x^(3/2),s}]]][[1,2]]Sqrt[x]+2 (1/4-I/4) (-1)^(3/4) Sqrt[x],{Inverse::luc}]
]


End[]
