(* Mathematica Test File *)

TestSuite[{
	"Tests/FunTest.mt"
	,
	"Tests/HastingsMcLeod.mt"
	,
	"Tests/PainleveIINegativeContour2.mt"
	,
	"Tests/PainleveIIPositive.mt"
	,
	"Tests/PainleveIIScaledNegative.mt"
	,
	"Tests/PainleveIISmall.mt"
	,
	"Tests/RHTest.mt"
	,
	"Tests/SpectralMatrixTest.mt"
	,
	"Tests/LFunCauchyMatrixTest.mt"
	,
	"Tests/CurveFunTest.mt"
	,
	"Tests/PFunTest.mt"
	,
	"Tests/ParametrixTest.mt"
	,
	"Tests/CauchyInverseTest.mt"
	,
	"Tests/CauchyDTest.mt"
}]