(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage[$CommonPackage];


PFun::usage="PFun[c0,p0,n] defines a function taking the value c0 and the point p0.";

PointDomainQ;
ToUnitPoint;


UnitPoint;
UnitPointFunQ;
MapToPoint;
MapFromPoint;
MapToPointD;
Begin["Private`"];

PointDomainQ[_Point]:=True;
PointDomainQ[_]:=False;

DomainQ[_?PointDomainQ]:=True;
DomainMemberQ[d_Point,x_]:=Abs[x-d[[1]]]<=10 $MachineTolerance;


UnitPoint=Point[0];
UnitPointFunQ[f_PFun]:=N[Domain[f]]==N[UnitPoint];
UnitPointFunQ[_]:=False;



MapToPoint[f_PFun,z_]:=MapToPoint[f//Domain,z];
MapFromPoint[f_PFun,z_]:=MapFromPoint[f//Domain,z];
MapToPointD[f_PFun,z_]:=MapToPointD[f//Domain,z];
MapFromPointD[f_PFun,z_]:=MapFromPointD[f//Domain,z];

MapToPoint[Point[z0_],z_]:=z-z0;
MapFromPoint[Point[z0_],z_]:=z+z0;

MapToPointD[Point[z0_],z_]:=1;
MapFromPointD[Point[z0_],z_]:=1;


End[];



Begin["Private`"];


Points[Point[z0_],1]:={z0};

End[];



Begin["Private`"];


DomainPlot[Point[z0_],opts___]:=
Graphics[{Thick,Blue,PointSize[Large],Arrowheads[Medium],
Point[{Re[z0],Im[z0]}]},opts,Axes->True];


PFun[c0_,d_][z_]:=c0[[1]];
PFun[c0_?ScalarQ,d_]:=PFun[{c0},d];
PFun[c0:{_,_,___},d_]:=PFun[{c0},d];
PFun[f_?(NotListOrPatternQ[#]&&!ScalarQ[#] &&!ScalarQ[First[Flatten[#]]]&)&,d_,1]:=PFun[{f[d[[1]]]},d];
PFun[f_?(NotListOrPatternQ[#]&&!ScalarQ[#]&&!ScalarQ[First[Flatten[#]]]&)&,d_,opts:OptionsPattern[]]:=PFun[f,d,1];


PFun/:Values[PFun[c0_,_]]:=c0;
FiniteValues[pf_PFun]:=Values[pf];
Domain[PFun[_,d_]]:=d;

SetupFun[PFun];

Mean[f_PFun]^:=f//Values//First;


FinitePoints[if_PFun]:=if//Points;

FiniteRealPoints[if_PFun]:=if//FinitePoints//Re;
End[];




Begin["Private`"];

ToUnitPoint[lf_PFun]:=SetDomain[lf,UnitPoint];
End[];




Begin["Private`"];


FromValueList[f_PFun?ScalarFunQ,ls_]:=PFun[ls,Domain[f]];
FromValueList[f_PFun?MatrixFunQ,ls_]:=PFun[{PartitionList[ls,f//Dimensions]},f//Domain];
FromValueList[f_PFun?VectorFunQ,ls_]:=PFun[{ls},f//Domain];

ZeroAtInfinityFun[f_List,d_?PointDomainQ]:=PFun[f,d];


End[];






Begin["Private`"];


DiagonalMatrix[f_PFun]^:=f//Values//DiagonalMatrix;
IdentityMatrix[f_PFun]^:=f//Length//IdentityMatrix;


Fun[f_,d_?PointDomainQ,opts___]:=PFun[f,d,opts];



End[];
EndPackage[];
